apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageos-scheduler
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - args:
        - kube-scheduler
        - --config=/scheduler/config.yaml
        - -v=4
        image: kube-scheduler
        imagePullPolicy: IfNotPresent
        name: storageos-scheduler
        volumeMounts:
        - name: config
          mountPath: /scheduler
      dnsPolicy: ClusterFirst
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      serviceAccountName: storageos-scheduler-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: node.kubernetes.io/disk-pressure
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 30
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 30
      volumes:
      - name: config
        configMap:
          name: storageos-scheduler-config
